### PR TITLE
TVB-2719 Add more surface data tests

### PR DESCRIPTION
**Pull request by ayan-b**

### CODE REVIEW

**Comment by liadomide** [comment]
These extra surfaces tested are good to have in the codebase, but not in the resulting Pypi (whl) packages. 
Could you pls include a Manifest.in file and exclude files data/*/* from the results, together with the test....py referring to them ?

**Review by liadomide — APPROVED** [review]

**Comment by ayan-b** [comment]
Not really sure why CI is not running, in my namespace here's the run: https://travis-ci.com/github/ayan-b/tvb-geodesic/builds/175553675

**Review by liadomide — APPROVED** [review]

**Comment by ayan-b** [comment]
Closing and reopening to trigger travis build.

**Comment by ayan-b** [comment]
In master, travis CI is triggered so no worries! :tada:

**Pull request merged**
